#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"
source ${PROJECT_ROOT}/config.sh

echo PROJECT_ROOT

echo "Building Docker image..."
docker build -t ${PROJECT_NAME} ${PROJECT_ROOT}
