#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"
source ${PROJECT_ROOT}/config.sh

docker run -it \
  -p 8899:8899 \
  --name=${PROJECT_NAME} \
  --volume ${PROJECT_ROOT}/ComputerVisionProject:/ComputerVisionProject \
  --hostname=cvproject.local  \
  --rm \
  ${PROJECT_NAME}
